### PR TITLE
first stab at `mj install`

### PR DESCRIPTION
**Pull request by rueckstiess**
##### current progress

`mj install` will 
- run `npm install -g jshint`    (requirement for SublimeLinter-jshint)

and additionally,  if `--sublime` supplied, search for sublime installation to
- register several plugins with Package Control (if installed):   `Jade`, `LESS`, `jsfmt`, `SublimeLinter`, `SublimeLinter-jshint`, `Git`
- hide dot (.*) files via User preferences setting

[Review on Reviewable](https://reviewable.io/reviews/mongodb-js/mj/12)

### CODE REVIEW

**Comment by imlucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mj/12)

Reviewed files:
- commands/demo.js @ r1

---

<sup>**[commands/install.js, line 132 [r1]](https://reviewable.io:443/reviews/mongodb-js/mj/12#-Jkrhtm8Fn7KkKZmXVgD)** ([raw file](https://github.com/mongodb-js/mj/blob/4eed9afcf9eb4ad79003aaefe90c4180f1f8da07/commands/install.js#L132)):</sup>
If already installed, `npm install` will just be a noop so don't worry

---

<sup>**[package.json, line 18 [r1]](https://reviewable.io:443/reviews/mongodb-js/mj/12#-Jkrj3PauGkJar8bQyN2)** ([raw file](https://github.com/mongodb-js/mj/blob/4eed9afcf9eb4ad79003aaefe90c4180f1f8da07/package.json#L18)):</sup>
Why all of lodash when you're just using `amp-each` and `amp-has`?

---

<sup>**[test/index.test.js, line 95 [r1]](https://reviewable.io:443/reviews/mongodb-js/mj/12#-JkriMjwXMgxwtFYP3CN)** ([raw file](https://github.com/mongodb-js/mj/blob/4eed9afcf9eb4ad79003aaefe90c4180f1f8da07/test/index.test.js#L95)):</sup>
Use `if(err) return cb(err);` or `assert.ifError(err);` instead

---

<sup>**[test/index.test.js, line 106 [r1]](https://reviewable.io:443/reviews/mongodb-js/mj/12#-Jkri7eqQYjSgaaL-sgq)** ([raw file](https://github.com/mongodb-js/mj/blob/4eed9afcf9eb4ad79003aaefe90c4180f1f8da07/test/index.test.js#L106)):</sup>
Use `if(err) return cb(err);` or `assert.ifError(err);` instead

---

<sup>**[util/run_steps.js, line 9 [r1]](https://reviewable.io:443/reviews/mongodb-js/mj/12#-Jkrigu3yjrUG5ePYapx)** ([raw file](https://github.com/mongodb-js/mj/blob/4eed9afcf9eb4ad79003aaefe90c4180f1f8da07/util/run_steps.js#L9)):</sup>
If we're going to use jsdocs, let's use them everywhere and format properly https://www.npmjs.com/package/dox

---

**Comment by imlucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mj/12)

Reviewed files:
- commands/check.js @ r1
- commands/install.js @ r1
- docopts/create.docopt @ r1
- docopts/demo.docopt @ r1
- docopts/help.docopt @ r1
- docopts/install.docopt @ r1
- package.json @ r1
- test/index.test.js @ r1
- util/run_steps.js @ r1
- util/symbols.js @ r1

---

**Comment by imlucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mj/12)

---

Looking good.  Just a few questions I'm curious about.

---

**Comment by rueckstiess** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mj/12)

---

<sup>**[commands/install.js, line 132 [r1]](https://reviewable.io:443/reviews/mongodb-js/mj/12#-Jkrhtm8Fn7KkKZmXVgD)** ([raw file](https://github.com/mongodb-js/mj/blob/4eed9afcf9eb4ad79003aaefe90c4180f1f8da07/commands/install.js#L132)):</sup>
I know but it takes 3-5 seconds. Would be nice if it was instant. 

---

<sup>**[package.json, line 18 [r1]](https://reviewable.io:443/reviews/mongodb-js/mj/12#-Jkrj3PauGkJar8bQyN2)** ([raw file](https://github.com/mongodb-js/mj/blob/4eed9afcf9eb4ad79003aaefe90c4180f1f8da07/package.json#L18)):</sup>
good point, will replace with amp-*.

---

**Comment by imlucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mj/12)

---

<sup>**[commands/install.js, line 132 [r1]](https://reviewable.io:443/reviews/mongodb-js/mj/12#-Jkrhtm8Fn7KkKZmXVgD)** ([raw file](https://github.com/mongodb-js/mj/blob/4eed9afcf9eb4ad79003aaefe90c4180f1f8da07/commands/install.js#L132)):</sup>
Ah I see.  Comment made me think you needed for sanity.  This will cut it down to ~500ms:

``` javascript
var exec = require('child_process').exec;

/**
 * Check if a module with `name` is installed globally.
 *
 * @param {String} name of the module, e.g. jshint
 * @param {Function} fn (error, exists)
 */
function isModuleInstalledGlobally(name, fn){
  var cmd = 'npm ls --global --production --json --depth=0';
  exec(cmd, function(err, stdout){
    if(err) return fn(err);

    var data = JSON.parse(stdout);
    var installed = data.dependencies[name];
    fn(null, (installed !== undefined));
  });
}
// npm install pretty-hrtime
var prettyHrtime = require('pretty-hrtime');
var start = process.hrtime();
isModuleInstalledGlobally('jshint', function(err, installed){
  var duration = process.hrtime(start);
  console.log('exec of npm ls took', prettyHrtime(duration));

  if(err) return console.error(err);
  console.log('jshint installed globally?', installed);
});
```

---

**Comment by imlucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mj/12)

Reviewed files:
- commands/install.js @ r2
- package.json @ r2
- test/index.test.js @ r2
- util/run_steps.js @ r2

---

**Comment by imlucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mj/12)

---

:thumbsup:

---

**Comment by rueckstiess** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mj/12)

---

<sup>**[commands/install.js, line 132 [r1]](https://reviewable.io:443/reviews/mongodb-js/mj/12#-Jkrhtm8Fn7KkKZmXVgD)** ([raw file](https://github.com/mongodb-js/mj/blob/4eed9afcf9eb4ad79003aaefe90c4180f1f8da07/commands/install.js#L132)):</sup>
Perfect, thanks! `--json` is great.

Replacing and merging in PR.

---

**Pull request merged**
